### ISSUE TITLE
Two scrollbars appear in navigation pane

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#10]
See the screenshot below: 

<img width="362" alt="image" src="https://github.com/OneBusAway/onebusaway-docs/assets/2254/621963bc-69cd-48be-9d85-d42eb93b4add">

there should only be a single scrollbar (the right-most one), and the site's title and logo should not scroll out of view when scrolling.

**Comment by Ajay9330** [comment]
![image](https://github.com/OneBusAway/onebusaway-docs/assets/140816066/bb274637-b67b-4fdb-b193-b1cc7c615586)
i have already fixed issue before of raising it but there is problem with pull request

**Comment by ankitkumar748846** [comment]
I would like to work on this issue
