### ISSUE TITLE
🐞 Add dark mode support to JSON Editor

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The new JSONEditor needs support for dark mode

### Steps To Reproduce

1. use dark mode
2. open http://localhost:4000/api/where/methods/vehicles-for-agency

### Expected Behavior

The JSONEditor's theme does not have a bright, white background, but instead a background that is suitable for use with dark mode.

### Screenshots

<img width="1688" alt="image" src="https://github.com/OneBusAway/onebusaway-docs/assets/2254/795e450e-dc68-4dfd-ac8e-1992c9e761ee">

### Are you working on this issue?

No

**Comment by ankitkumar748846** [comment]
Please assign me this issue @aaronbrethorst  sir

**Comment by Ajay9330** [comment]
May i work on this bug?

**Comment by Ajay9330** [comment]
i had research about this issue, but still unable to solve it without cdn,
- https://github.com/josdejong/jsoneditor/issues/1048
- https://github.com/josdejong/jsoneditor/issues/335

## Here is the approach which i have tried
- i also imported the themes form the 'ace-builds'(stored inside the node_modules) but still not able to resolve, actually jsoneditor is build on the top of 'ace-editor'
- `  editor.aceEditor.setTheme('ace-builds/src/tomorrow_night')`
- `  const options = {
    mode: 'code',
    mode:'ace/theme/tomorrow_night',
    modes: ['code', 'view'], // allowed modes
  }`
- in ace-build there is a lot of themes (js and css) but unable to find how to use it jsoneditor
![image](https://github.com/OneBusAway/onebusaway-docs/assets/140816066/d02e0720-adc9-450e-94b9-7f6a3274c64d)


here is cdn solution,
- https://jsbin.com/fehafe/edit?html,output

we can also use custom css also
