### ISSUE TITLE
Interested in Contributing to the Developer Documentation Website Enhancement Project during GSOC

### ISSUE THREAD

**Issue by samipak458** [OneBusAway/onebusaway-docs#111]
Hey @aaronbrethorst,

I am writing to express my strong interest in the Developer Documentation Website Enhancement project at Open Transit Software Foundation as part of Google Summer of Code. After reviewing the project details, I believe my skills and background make me well-equipped to contribute meaningfully to this initiative.

Having previously contributed to the OpenSearch project and Microsoft Learn modules, I have gained valuable experience in open source collaboration and documentation improvement, which I believe aligns well with the goals of this project.

I am particularly drawn to this project due to my passion for ensuring clear and cohesive developer documentation. I am eager to take on the challenge of unifying disparate sources of documentation, refining the website, and creating a seamless pipeline for updating Java API docs.

### Issue
Currently, I am experiencing difficulty joining the Slack community due to an error regarding the email domain. I would greatly appreciate any guidance on alternative ways to get involved in the community, access relevant resources, and connect with potential mentors.

I look forward to the opportunity to discuss this project further and to learn more about the next steps in the application process. Your mentorship and insights will be invaluable as I navigate my way through the Open Transit Software Foundation's programs.

Thank you for considering my interest, and I am enthusiastic about the possibility of contributing to this initiative.

### Additional context

GSOC

### Are you working on this?

Yes

**Comment by samipak458** [comment]
@aaronbrethorst kindly guide?

**Comment by aaronbrethorst** [comment]
you can join here: https://join.slack.com/t/onebusaway/shared_invite/zt-2f1aikj0j-_4O2dSUCr43hpUWaa3ER7g
