### ISSUE TITLE
[FEATURE]: Add issue info to improve readability

### ISSUE THREAD

**Issue by Geetika-verma01** [OneBusAway/onebusaway-docs#12]
I'd like to suggest one feature here.
Instead of just showing issue number in `/release-notes`, we should also append the issue detail that will make it more readable.
It'll help the user to quickly grasp the issue detail instead to checking it again and again on github.

Attaching screenshot for better info:
![image](https://github.com/OneBusAway/onebusaway-docs/assets/111682607/64dda674-a493-477f-bf7b-6b461650472a)

**Comment by Geetika-verma01** [comment]
Hii all, 
I'd like to contribute to this feature as part of gsoc.
Please assign me this issue.
Many thanks

**Comment by aaronbrethorst** [comment]
thanks for the suggestion. however, I think this needs to be the responsibility of the developer who adds new release notes. also, the release notes page is wildly out of date right now. improving the release notes for a years-old release won't benefit developers.
