### ISSUE TITLE
🐞 Bug unable to click on the footer links due to the overflow

### ISSUE THREAD

**Issue by Ajay9330** [OneBusAway/onebusaway-docs#120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when width of the screen in range of (1537,1772) the footer links (github,blog etc) are not working due to overflow of the right-topbar

### Steps To Reproduce

1. launch the website
2. set screen width == 1550px (use dev tool of the browser)
3. scroll to footer 
4. click on the icons of footer (github,blog, etc)

### Expected Behavior

on clicking links should redirect the user to respective url

### Screenshots

![image](https://github.com/OneBusAway/onebusaway-docs/assets/140816066/1a128e13-5f0b-47f2-8922-d060fd0f087e)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by ankitkumar748846** [comment]
I will work on this issue @Ajay9330 @aaronbrethorst

**Comment by PeritusDeveloper** [comment]
I am **Shraddha Basarikatti**, a prospective GSoC applicant interested in contributing to `Enhance our developer documentation website`. I've just submitted a pull request addressing the bug outlined in this issue. I am eager to delve deeper into resolving issues and enhancing the developer documentation further.

Looking forward to collaborating with you all!
