### ISSUE TITLE
Overflow issue in small width (if width <=433px)

### ISSUE THREAD

**Issue by Ajay9330** [OneBusAway/onebusaway-docs#15]
### Steps to check issue:

1. launch site, go to mobile view
2. go to the "/release-notes" route of the site (you can go by clicking on the  link of navigation pan which is "Release Notes" also)
3. zoom out and scroll down

you will get
## Issue: overflow in x
 ![image](https://github.com/OneBusAway/onebusaway-docs/assets/140816066/6d62fab6-822f-4456-95f0-0b57359493db)
## Cause by the long ,non-breaking words in code element
![image](https://github.com/OneBusAway/onebusaway-docs/assets/140816066/19a3974b-beee-4731-93e1-f480e878c8be)

**Comment by Ajay9330** [comment]
Same issue here also at navlink: register-alarm-for-arrival-and-departure-at-stop
![image](https://github.com/OneBusAway/onebusaway-docs/assets/140816066/d63dbce7-214e-47b8-89c8-5496211d1ac9)

**Comment by mokshablr** [comment]
I can wrap the words by breaking them if that's how you would like to go about it @aaronbrethorst. Current fix only works for the background ending before full-width.
A simple `class="break-words"` in the article element will fix it.

**Comment by Ajay9330** [comment]
Yes @mokshablr right i have added word-break and word-wrap also but we have to apply for those which are actually causing the issue of overflowing one by one for smaller screen only or we can,
If we apply globally then the other word will also get a break in wide screen which doesn't actually cause the overflow,
There is also another solution which is overflow auto for x, but which will be best?

**Comment by aaronbrethorst** [comment]
thanks for reporting @Ajay9330
