### ISSUE TITLE
Mobile: Navigation pane doesn't appear if you try to show it while scrolled down the page

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#2]
Repro:

1. Launch the site on a mobile device (or desktop, small viewport)
2. Scroll down to the bottom of a longish page.
3. Tap the hamburger button.

Expected: navigation pane appears.
Actual: navigation pane is not shown, because it's 👆 a few screen lengths away.

The fix should be pretty straightforward: apply `position: absolute` to the navigation pane on viewports smaller than large.

**Comment by Akhilesh-max** [comment]
@aaronbrethorst 
Please assign this issue to me. I’ve attempted to implement the proposed solution, but it ain't seems to be working or I might have misunderstood something. I tried applying `position:absolute` in the file `src/_partials/_navbar.erb`, but it didn’t yield the expected results.

`<nav class="pl-5 pt-10 lg:p-0 lg:block max-h-[100svh] overflow-y-scroll md:absolute" :class="{ 'hidden': !nav_open }">
`
This is my first time working with Tailwind, and will need to further look into it.  I am looking for you input on the above concern. 

Thanks you.

**Comment by aaronbrethorst** [comment]
thanks for looking into it @Akhilesh-max

**Comment by aaronbrethorst** [comment]
@Akhilesh-max I'm going to remove your assignment from this issue. Please feel free to push up a PR if you're actively working on it

**Comment by tarunsinghofficial** [comment]
Hi @aaronbrethorst, I found the same issue when on smaller screens. Can you please assign this issue to me, so that I can look into it and try to fix it? 

Thanks and happy coding!

**Comment by aaronbrethorst** [comment]
@tarunsinghofficial sure, I look forward to your fix!

**Comment by aaronbrethorst** [comment]
This is fixed
