### ISSUE TITLE
Document the config.json API endpoint

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#26]
A new REST API Methods page should be added for config.json. Here's an example URL: https://api.pugetsound.onebusaway.org/api/where/config.json?&key=TEST

**Comment by ankitkumar748846** [comment]
I would like to work on this issue.

**Comment by aaronbrethorst** [comment]
@ankitkumar748846 Sure, go wild. I'd like to see a draft PR up within 72 hours. Doesn't have to be complete. Just show some progress.

**Comment by ankitkumar748846** [comment]
Sir, I have implemented the feature in the config.json file as you assigned me the issue. Could you please confirm what additional content I should display on the config method webpage? 
@aaronbrethorst 

![1](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/0119aa31-0978-440d-8eef-a8aaf73eb7c9)
![2](https://github.com/ankitkumar748846/private/assets/109648585/8cc256a3-b3b1-478b-bdfd-b9ebd79172c2)
![3](https://github.com/ankitkumar748846/private/assets/109648585/86216d5f-2a91-45c0-bb7a-80f260190729)
