### ISSUE TITLE
Tighten up inter-paragraph padding

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#3]
The padding in between paragraphs feels unnecessarily generous. Let's decrease it by 25%(?) to increase information density per screen.

**Comment by ankitkumar748846** [comment]
I would like to work on this issue.

**Comment by aaronbrethorst** [comment]
awesome, thanks @ankitkumar748846! looking forward to your PR.

**Comment by ankitkumar748846** [comment]
Using a "where" in CSS will create an issue and it will not support for smaller version and cause unexpected behavior in the rendering of your webpage.
You can refer this :
[Link](https://caniuse.com/?search=%3Awhere)
 @aaronbrethorst WDYT??
@CLAassistant
