### ISSUE TITLE
feat: Prev and Next Buttons for Enhanced Navigation Experience

### ISSUE THREAD

**Issue by ankitkumar748846** [OneBusAway/onebusaway-docs#39]
### Is your feature request related to a problem? Please describe

Lack of prev and next buttons: Users must manually navigate, leading to frustration, increased effort, and loss of engagement.

Before:
![Before](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/47c7ebdd-5764-4384-a845-213d461d9727)

After:
![Prev_Next](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/2be09c6c-d0a9-480a-bb5d-c2724a7e5555)

### Describe the solution you'd like

Introduce prev and next buttons: Enhance user experience by providing intuitive navigation, reducing effort, and increasing engagement on the website.

After:
![Prev_Next](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/f057f939-9810-4e2a-86be-54e0ccf534db)

### Are you working on this?

Yes

**Comment by aaronbrethorst** [comment]
see comments on PR
