### ISSUE TITLE
Dead links to be redirected

### ISSUE THREAD

**Issue by mokshablr** [OneBusAway/onebusaway-docs#5]
Here is a list of broken links that we should look into fixing to make the documentation website better!
I will be looking into fixing these as well.

S no. | Error | URL | Anchor Text | Linked From
-- | -- | -- | -- | --
1 | -1 Invalid URL | http://localhost:8080/ | http://localhost:8080/ | https://developer.onebusaway.org/guides/quickstart-guide
2 | 404 Not Found | https://developer.onebusaway.org/oba-configs/index.html | list of configuration parameters | https://developer.onebusaway.org/guides/installation-guide
3 | 404 Not Found | https://developer.onebusaway.org/guides/sms-webapp-configuration-guide | SMS Config | https://developer.onebusaway.org/guides/installation-guide
4 | 404 Not Found | https://repo.camsys-apps.com/releases/org/onebusaway/onebusaway-status-agent/2.4.18-cs/onebusaway-status-agent-2.4.18-cs-withAllDependencies.jar | onebusaway-status-agent-2.4.18-cs-withAllDependencies.jar | https://developer.onebusaway.org/downloads
5 | 404 Not Found | https://repo.camsys-apps.com/releases/org/onebusaway/onebusaway-status-agent/2.4.18-cs/onebusaway-status-agent-2.4.18-cs.jar | onebusaway-status-agent-2.4.18-cs.jar | https://developer.onebusaway.org/downloads
6 | -1 Invalid URL | http://localhost:8080/where/standard/agencies.action | http://localhost:8080/where/standard/agencies.action | https://developer.onebusaway.org/guides/troubleshooting-guide
7 | -1 Invalid URL | http://localhost:8080/where/standard/ | http://localhost:8080/where/standard/ | https://developer.onebusaway.org/guides/troubleshooting-guide
8 | -1 Invalid URL | http://localhost:8080/where/standard/stop.action?id=AGENCYID_STOPID | http://localhost:8080/where/standard/stop.action?id=AGENCYID_STOPID | https://developer.onebusaway.org/guides/troubleshooting-guide
9 | -1 Invalid URL | http://localhost:8080/api/where/agencies-with-coverage.xml?key=TEST | http://localhost:8080/api/where/agencies-with-coverage.xml?key=TEST | https://developer.onebusaway.org/guides/troubleshooting-guide
10 | 404 Not Found | https://developer.onebusaway.org/api/where/methods/stops.html | method documentation | https://developer.onebusaway.org/guides/troubleshooting-guide
11 | -1 Invalid URL | http://localhost:8080/api/where/routes-for-agency/AGENCYID.xml?key=TEST | http://localhost:8080/api/where/routes-for-agency/AGENCYID.xml?key=TEST | https://developer.onebusaway.org/guides/troubleshooting-guide
12 | -1 Invalid URL | http://localhost:8080/api/where/stop-ids-for-agency/AGENCYID.xml?key=TEST | http://localhost:8080/api/where/stop-ids-for-agency/AGENCYID.xml?key=TEST | https://developer.onebusaway.org/guides/troubleshooting-guide
13 | 404 Not Found | https://developer.onebusaway.org/api/where/elements/list-result.html | list result | https://developer.onebusaway.org/api/where/methods/stops-for-location
14 | 404 Not Found | https://developer.onebusaway.org/api/where/elements/stop.html | &lt;stop/&gt; element | https://developer.onebusaway.org/api/where/methods/stops-for-location
15 | -1 Not found: The server name or address could not be resolved | http://user47094.vs.easily.co.uk/siri/ | SIRI | https://developer.onebusaway.org/api/where/elements/situation
16 | 404 Not Found | https://developer.onebusaway.org/guides/wiki/Database-Guide | Database Setup and Configuration Guide | https://developer.onebusaway.org/guides/wiki/oba-1x-developer-guide
17 | 404 Not Found | https://developer.onebusaway.org/guides/wiki/nextbus.com/xmlFeedDocs/NextBusXMLFeed.pdf | NextBus API | https://developer.onebusaway.org/guides/wiki/gtfs-realtime-resources
18 | -1 Invalid URL | http://localhost:8080/onebusaway-transit-data-federation-webapp/ | http://localhost:8080/onebusaway-transit-data-federation-webapp/ | https://developer.onebusaway.org/guides/wiki/enterprise-webapp-configuration
19 | -1 Invalid URL | http://localhost:8080/onebusaway-api-webapp/api/where/config.json?key=TEST | http://localhost:8080/onebusaway-api-webapp/api/where/config.json?key=TEST | https://developer.onebusaway.org/guides/wiki/enterprise-webapp-configuration
20 | -1 Invalid URL | http://localhost:8080/routes | http://localhost:8080/routes | https://developer.onebusaway.org/guides/wiki/enterprise-webapp-configuration
21 | -1 Invalid URL | http://localhost:8080/api/where/stops-for-location.xml?key=TEST&lat=37.785045&lon=-122.407049 | http://localhost:8080/api/where/stops-for-location.xml?key=TEST&amp;lat=37.785045&amp;lon=-122.407049 | https://developer.onebusaway.org/guides/wiki/gtfs-realtime-quickstart
22 | 403 Forbidden | https://camo.githubusercontent.com/75dc67e42c838144f7d5f6f2901461c0272888ab/687474703a2f2f646576656c6f7065722e6f6e65627573617761792e6f72672f6d6f64756c65732f6f6e65627573617761792d6170706c69636174696f6e2d6d6f64756c65732f63757272656e742f6775696465732f517569636b53746172744775692e706e67 | img/src | https://developer.onebusaway.org/guides/wiki/gtfs-realtime-quickstart
23 | 404 Not Found | https://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/index.html | REST API [301 from http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/index.html] | https://developer.onebusaway.org/guides/wiki/oba-1x-developer-guide
24 | 404 Not Found | https://www.mbta.com:443/rider_tools/developers/default.asp?id=21895 | MBTA’s GTFS data [301 from http://www.mbta.com/rider_tools/developers/default.asp?id=21895] | https://developer.onebusaway.org/guides/wiki/oba-1x-developer-guide
25 | 404 Not Found | https://www.mbta.com:443/rider_tools/developers/default.asp?id=22393 | MBTA GTFS-realtime [301 from http://www.mbta.com/rider_tools/developers/default.asp?id=22393] | https://developer.onebusaway.org/guides/wiki/oba-1x-developer-guide
26 | 404 Not Found | https://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/stops-for-location.html | stops-for-location [301 from http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/stops-for-location.html] | https://developer.onebusaway.org/guides/wiki/gtfs-realtime-quickstart
27 | 404 Not Found | https://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrival-and-departure-for-stop.html | arrivals-and-departures-for-stop [301 from http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/methods/arrival-and-departure-for-stop.html] | https://developer.onebusaway.org/guides/wiki/gtfs-realtime-quickstart
28 | 404 Not Found | https://github.com/OneBusAway/onebusaway-docker/tree/main/config | Docker repo [302 from https://github.com/OneBusAway/onebusaway-docker/tree/master/config] | https://developer.onebusaway.org/guides/wiki/enterprise-webapp-configuration
29 | 404 Not Found | https://api.pugetsound.onebusaway.org/api/where/search/route.json?input=crystal&key=TEST | http://api.pugetsound.onebusaway.org/api/where/search/route.json?input=crystal&amp;key=TEST [301 from http://api.pugetsound.onebusaway.org/api/where/search/route.json?input=crystal&key=TEST] | https://developer.onebusaway.org/api/where/search/route

Note: Some of the links are used for explanation purposes. Eg: 1st localhost link is used to demonstrate starting up of the webapp.

**Comment by aaronbrethorst** [comment]
All of the localhost links that refer to a user's local development environment should be left as-is.

**Comment by aaronbrethorst** [comment]
fixed in #8
