### ISSUE TITLE
Inactive Links on Website

### ISSUE THREAD

**Issue by ankitkumar748846** [OneBusAway/onebusaway-docs#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Some links on the website are inactive, leading to a poor user experience and potential frustration for users trying to access relevant content. In certain pages of the REST API METHODS, specifically within sections such as "Cancel Alarm" and "Vehicles for Agency," as well as "Arrival and Departure for Stop," inactive links are observed. 

### Steps To Reproduce

1.Click on the "REST API METHODS" section in the sidebar to access the main section containing various subsections.
2.Within the "REST API METHODS" section, select any of the subsections, such as "cancel-alarm," "vehicles-for-agency," or "arrival-and-departure-for-stop."
 3.After clicking on the desired subsection, the page will reload, displaying the content related to that subsection.
4.Within the subsection page, "Sample Request" section.
5.Copy the link associated with the "Sample Request."
6.Open a new tab in your browser (e.g., Google Chrome).
7.Paste the URL

### Expected Behavior
   http://api.onebusaway.org/api/where/vehicles-for-agency/1.json?key=TEST
   https://api.pugetsound.onebusaway.org/api/where/cancel_alarm/1_00859082-9b9d-4f72-a89f-c4be0e2cf01a.json
### Screenshots

![link](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/0c966bbc-04c3-40eb-aaab-65087d0ae4b4)

_No response_

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

**Comment by aaronbrethorst** [comment]
I have deleted the `cancel-alarms` and `register-alarms` pages. Those APIs don't work anymore. As far as the others go, replace instances of `api.onebusaway.org` with `api.pugetsound.onebusaway.org`.

**Comment by ankitkumar748846** [comment]
okay sir @aaronbrethorst
