### ISSUE TITLE
🐞 Add button title to code block copy buttons

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In #50, we gained the ability to copy code snippets from blocks throughout the website (thanks @ankitkumar748846!). However, these buttons are not labeled for screenreader. They should be given a title attribute "Copy Code Snippet"

### Steps To Reproduce

look at index.js where these buttons are created

### Expected Behavior

they should have a title attribute labeled "Copy Code Snippet"

### Screenshots

<img width="850" alt="image" src="https://github.com/OneBusAway/onebusaway-docs/assets/2254/261fee11-07bc-4aef-9809-dc5e1bc40bfb">

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by ankitkumar748846** [comment]
@aaronbrethorst   I would like to work on this issue

**Comment by aaronbrethorst** [comment]
go for it @ankitkumar748846
