### ISSUE TITLE
docs: Sample Response on a Webpage not in a JSON Format 

### ISSUE THREAD

**Issue by ankitkumar748846** [OneBusAway/onebusaway-docs#66]
### Is your feature request related to a problem? Please describe

The Sample Request  that is available is in JSON format but the Sample Response section is not in JSON Format.

![Linkjson](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/747aa95a-4552-4603-a329-6959201af875)

![responseXML](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/cc214d50-ca23-4c43-a583-cd1521dbd28e)

### Describe the solution you'd like

Sample Request and Sample Response both  should be in JSON 

![3](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/ac12bae6-3ee3-4f0e-8a89-428f3e93e3d2)

![4](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/2dba5ad5-f9b0-4b08-82f4-3d0a40325365)

### Are you working on this?

Yes

**Comment by aaronbrethorst** [comment]
I started fixing this with #102 - I look forward to you building off that work.

**Comment by ankitkumar748846** [comment]
@aaronbrethorst  Okay Sir, Some of the API links are active and returning a status code of 200. Should I create a pull request, sir?

**Comment by aaronbrethorst** [comment]
I've taken care of this.
