### ISSUE TITLE
feat: Create a subsection on the right side of the web page.

### ISSUE THREAD

**Issue by ankitkumar748846** [OneBusAway/onebusaway-docs#75]
### Is your feature request related to a problem? Please describe

Lack of subsection on the right side of the web page.

### Describe the solution you'd like

Create a subsection on the right side of the webpage that contains all the headings of the page.

Screenshot:
![Subsection](https://github.com/OneBusAway/onebusaway-docs/assets/109648585/16d355d3-686a-497d-88da-f100492bb7d0)

### Are you working on this?

Yes

**Comment by ankitkumar748846** [comment]
@aaronbrethorst  Please assign me this issue if it looks good.

**Comment by aaronbrethorst** [comment]
How are you planning on creating the subsection headings? Javascript?

**Comment by ankitkumar748846** [comment]
@aaronbrethorst  Yes Sir, I will be using Javascript.

**Comment by aaronbrethorst** [comment]
cool, sounds good to me. I just wanted to make sure that existing pages wouldn't need to be modified to support this :)

**Comment by ankitkumar748846** [comment]
@aaronbrethorst Yes sir.
