### ISSUE TITLE
Change the heading link icon to a checkmark after copying

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-docs#97]
### Is your feature request related to a problem? Please describe

In #90, we gained the ability to copy a heading's link to the clipboard by clicking on it. This is a great addition, but it doesn't give the user any feedback that the copy event occurred. After clicking on the icon, the link icon should change to a checkmark, as seen on code snippets.

### Describe the solution you'd like

see above

### Are you working on this?

No

**Comment by tarunsinghofficial** [comment]
I'll work on this. Please assign.

**Comment by tarunsinghofficial** [comment]
Done. PR #109

**Comment by tarunsinghofficial** [comment]
> ### Is your feature request related to a problem? Please describe
> In #90, we gained the ability to copy a heading's link to the clipboard by clicking on it. This is a great addition, but it doesn't give the user any feedback that the copy event occurred. After clicking on the icon, the link icon should change to a checkmark, as seen on code snippets.
> 
> ### Describe the solution you'd like
> see above
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Are you working on this?
> No

Fixed #109
